(()=>{'use strict';
const KEY='marketMindV1',YEN=new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}),$=s=>document.querySelector(s);
const SEEDS=[['NVA','ネオビジョンAI','AI',4200,.32,.18,42],['QSC','クオンタムセミコン','半導体',3180,.24,.16,31],['CLD','クラウドリーフ','SaaS',2650,.28,.12,38],['HBR','ひかり銀行','銀行',1280,.06,.22,9],['MRC','ミライマート','小売',1860,.08,.07,18],['TBL','テーブルリンク','外食',940,.12,.09,24],['AST','アステラ自動車','自動車',2440,.07,.08,11],['PIX','ピクセルフォージ','ゲーム',3520,.18,.24,26],['CEL','セルノヴァ製薬','医薬品',4780,.15,.2,34],['URB','アーバンネスト','不動産',1640,.05,.14,10],['BLD','ブルーリッジ建設','建設',1180,.04,.06,8],['NXT','ネクサス通信','通信',2240,.05,.13,14],['TRD','東西グローバル商事','商社',2980,.09,.1,12],['HRX','ヒューマンクロス','人材',1540,.11,.08,19],['ECO','エコーカート','EC',2080,.21,.11,32],['LOG','ロジスフィア','物流',1370,.08,.07,16],['RBT','ロボティクスワン','ロボット',3860,.26,.19,36],['ENE','グリーンウェーブ電力','エネルギー',1760,.1,.1,15],['FOD','フードサイエンス','食品',1320,.04,.08,17],['SEC','セキュアゲート','セキュリティ',2940,.23,.15,33]];
const EXPLAIN={PER:'株価が1株利益の何倍か。低さだけでなく、成長率・利益の持続性・業種比較が必要です。',PBR:'株価が1株純資産の何倍か。1倍割れでも低ROEや赤字なら評価が低い理由があります。',ROE:'自己資本から利益を生む効率。借金で自己資本が薄い企業は見かけ上高くなる点に注意。',ROA:'総資産全体の利益効率。負債を含めた事業効率を確認できます。',EPS:'1株あたり純利益。株価の土台ですが、一時利益や株数の変化も確認します。',BPS:'1株あたり純資産。利益の蓄積で増えますが、資産の質も重要です。','営業利益率':'本業で売上の何%を利益にしたか。売上成長と同時に見ると質が分かります。','自己資本比率':'資産のうち返済不要の自己資本の割合。高低の適正値は業種で異なります。'};
const EVENTS=[
 {t:'AIインフラ需要が急増',d:'AI・半導体・セキュリティに追い風。期待も過熱気味です。',tags:['AI','半導体','セキュリティ'],v:.08},
 {t:'中央銀行が追加利上げ',d:'銀行の利ざやには追い風、高PER成長株の評価には逆風。',rate:.25,tags:['銀行'],v:.06,growth:-.035},
 {t:'原材料価格が上昇',d:'製造・外食・建設の利益率を圧迫します。',tags:['自動車','外食','建設'],v:-.07,margin:-.025},
 {t:'個人消費が回復',d:'小売・外食・ECに売上増加期待。',tags:['小売','外食','EC'],v:.055},
 {t:'円安が進行',d:'輸出比率の高い自動車・商社・半導体に追い風。',tags:['自動車','商社','半導体'],v:.05},
 {t:'景気後退懸念',d:'投資家がリスク回避。高PER銘柄ほど売られやすい局面。',all:-.035,growth:-.035},
 {t:'企業の自社株買いが相次ぐ',d:'資本効率改善への期待が市場心理を支えました。',all:.018},
 {t:'物流コストが低下',d:'EC・小売・物流の採算改善が期待されます。',tags:['EC','小売','物流'],v:.045,margin:.012}
];
const CYCLES=['景気回復','好景気','景気減速','不況'];
function makeCompanies(){return SEEDS.map((s,i)=>{let [ticker,name,sector,price,growth,margin,targetPE]=s;let revenue=8000+i*470,shares=8+i*.2,op=revenue*margin,net=op*.68,equity=revenue*(sector==='銀行'?1.7:.65),assets=equity/(sector==='銀行'?.09:.48),debt=Math.max(0,assets-equity)*.48;return{id:ticker,ticker,name,sector,price,prevPrice:price,growth,baseGrowth:growth,margin,targetPE,revenue,gross:revenue*(.38+(i%5)*.04),op,ordinary:op*.94,net,assets,equity,capital:equity*.96,shares,dividend:Math.round(net/shares*(.18+(i%4)*.1)),ocf:op*1.18,icf:-op*.55,fcf:op*.63,financing:-op*.18,cash:assets*.13,debt,history:[price],revenueHist:[revenue*.82,revenue*.9,revenue],opHist:[op*.76,op*.87,op],epsHist:[net/shares*.78,net/shares*.88,net/shares],reports:[],news:[]}})}
function fresh(){let companies=makeCompanies();return{version:2,started:false,difficulty:'beginner',year:2026,q:1,turn:0,cash:1e7,holdings:{},companies,rate:.5,cycle:0,sentiment:0,assets:[1e7],history:[],news:[],dividends:0,trades:0,quizDone:[],peak:1e7,maxDD:0}}
let state=load(),selected='NVA',sector='すべて',tab='overview',metric='price',range='ALL',tradeSide='buy';
function load(){try{let x=JSON.parse(localStorage.getItem(KEY));return x?.version===2?x:fresh()}catch{return fresh()}}function save(){localStorage.setItem(KEY,JSON.stringify(state))}function c(){return state.companies.find(x=>x.id===selected)}function money(n){return YEN.format(n||0)}function pct(n){return`${n>=0?'+':''}${(n||0).toFixed(1)}%`}function ratio(n,d){return d? n/d:0}
function metrics(x){let eps=x.net/x.shares,bps=x.equity/x.shares,per=x.price/eps,pbr=x.price/bps,roe=x.net/x.capital*100,roa=x.net/x.assets*100,market=x.price*x.shares,yieldPct=x.dividend/x.price*100,payout=x.dividend/eps*100;return{eps,bps,per,pbr,roe,roa,market,yieldPct,payout,opMargin:x.op/x.revenue*100,equityRatio:x.capital/x.assets*100,yoyRev:x.revenueHist.length>1?(x.revenueHist.at(-1)/x.revenueHist.at(-2)-1)*100:0,yoyOp:x.opHist.length>1?(x.opHist.at(-1)/x.opHist.at(-2)-1)*100:0,cagr:(Math.pow(x.revenueHist.at(-1)/x.revenueHist[0],1/Math.max(1,x.revenueHist.length-1))-1)*100}}
function total(){return state.cash+Object.entries(state.holdings).reduce((a,[id,h])=>a+state.companies.find(x=>x.id===id).price*h.qty,0)}
function render(){renderTop();renderList();renderCompany();renderPortfolio();renderHistory();save()}
function renderTop(){let t=total(),stock=t-state.cash,unreal=Object.entries(state.holdings).reduce((a,[id,h])=>{let x=state.companies.find(y=>y.id===id);return a+(x.price-h.avg)*h.qty},0);$('#period').textContent=`${state.year} Q${state.q}`;$('#cycle').textContent=CYCLES[state.cycle];$('#rate').textContent=state.rate.toFixed(2)+'%';$('#sentiment').textContent=state.sentiment>.03?'強気':state.sentiment<-.03?'弱気':'中立';$('#remaining').textContent=`${Math.max(0,10-state.turn/4).toFixed(2)}年`;$('#totalAssets').textContent=money(t);$('#totalReturn').textContent=pct((t/1e7-1)*100);$('#totalReturn').className=t>=1e7?'positive':'negative';$('#cash').textContent=money(state.cash);$('#cashRatio').textContent=`現金比率 ${Math.round(state.cash/t*100)}%`;$('#stockValue').textContent=money(stock);$('#positions').textContent=Object.keys(state.holdings).length+'銘柄';$('#unrealized').textContent=money(unreal);$('#unrealized').className=unreal>=0?'positive':'negative';$('#dividends').textContent='累計配当 '+money(state.dividends)}
function renderList(){let q=$('#search').value?.toLowerCase()||'',list=state.companies.filter(x=>(sector==='すべて'||x.sector===sector)&&(x.name+x.ticker+x.sector).toLowerCase().includes(q));$('#stockList').innerHTML=list.map(x=>{let ch=(x.price/x.prevPrice-1)*100;return`<button class="stock-row ${x.id===selected?'active':''}" data-id="${x.id}"><span><b>${x.name}</b><small>${x.ticker} · ${x.sector}</small></span><span class="right"><b>${money(x.price)}</b><small class="${ch>=0?'positive':'negative'}">${pct(ch)}</small></span></button>`}).join('');document.querySelectorAll('.stock-row').forEach(b=>b.onclick=()=>{selected=b.dataset.id;render()})}
function renderCompany(){let x=c(),m=metrics(x),ch=(x.price/x.prevPrice-1)*100;$('#ticker').textContent=`${x.ticker} / PRIME SIM`;$('#companyName').textContent=x.name;$('#sector').textContent=x.sector;$('#price').textContent=money(x.price);$('#change').textContent=pct(ch);$('#change').className=ch>=0?'positive':'negative';$('#marketCap').textContent='時価総額 '+unit(m.market);renderChart(x);renderAnalysis(x,m)}
function metricCard(k,v){return`<div class="metric"><span>${k}${EXPLAIN[k]?`<button class="help" data-help="${k}">?</button>`:''}</span><strong>${v}</strong></div>`}
function insight(x,m){let a=[];if(m.per<12)a.push(m.yoyOp<0?'低PERですが利益減少が評価低迷の理由かもしれません。':'PERは低めですが、成長の持続性も確認しましょう。');if(m.per>30)a.push(m.yoyRev>15?'高PERには高成長への期待が含まれています。期待未達時の下落リスクもあります。':'成長に対してPERが高く、期待先行の可能性があります。');if(m.roe>15&&m.equityRatio<30)a.push('ROEは高い一方、自己資本比率が低く、財務レバレッジの影響があります。');if(m.yoyRev>0&&m.yoyOp<0)a.push('増収減益です。売上より利益率の悪化理由を確認しましょう。');if(x.fcf<0)a.push('フリーCFがマイナスです。成長投資か資金繰り悪化かを見分ける必要があります。');return a.join(' ')||'単一指標で結論を出さず、成長率・利益率・財務・市場期待を組み合わせて判断しましょう。'}
function renderAnalysis(x,m){let html='';if(tab==='overview')html=`<div class="metrics-grid">${metricCard('PER',m.per.toFixed(1)+'倍')}${metricCard('PBR',m.pbr.toFixed(2)+'倍')}${metricCard('ROE',m.roe.toFixed(1)+'%')}${metricCard('ROA',m.roa.toFixed(1)+'%')}${metricCard('EPS',money(m.eps))}${metricCard('BPS',money(m.bps))}${metricCard('配当利回り',m.yieldPct.toFixed(2)+'%')}</div><div class="insight">ANALYST LENS｜${insight(x,m)}</div>`;
if(tab==='performance')html=table(['指標','3期前','前期','最新','YoY'],[['売上高',...x.revenueHist.slice(-3).map(unit),pct(m.yoyRev)],['営業利益',...x.opHist.slice(-3).map(unit),pct(m.yoyOp)],['EPS',...x.epsHist.slice(-3).map(v=>money(v)),pct((x.epsHist.at(-1)/x.epsHist.at(-2)-1)*100)],['営業利益率','—','—',m.opMargin.toFixed(1)+'%',m.yoyOp-m.yoyRev>0?'改善':'悪化'],['売上CAGR','—','—',m.cagr.toFixed(1)+'%','複数年成長']]);
if(tab==='finance')html=table(['項目','金額 / 比率','読み方'],[['総資産',unit(x.assets),'事業に使う全資産'],['純資産',unit(x.equity),'負債を除いた価値'],['自己資本',unit(x.capital),'株主に帰属する資本'],['自己資本比率',m.equityRatio.toFixed(1)+'%','業種平均との差も確認'],['現金',unit(x.cash),'手元流動性'],['有利子負債',unit(x.debt),x.debt>x.cash*2?'現金に対して多め':'管理可能な水準']]);
if(tab==='cashflow')html=table(['CF項目','金額','評価'],[['営業CF',unit(x.ocf),x.ocf>0?'本業から現金流入':'要注意'],['投資CF',unit(x.icf),x.icf<0?'将来への投資':'資産売却の可能性'],['財務CF',unit(x.financing),x.financing<0?'返済・還元':'資金調達'],['フリーCF',unit(x.fcf),x.fcf>0?'自由に使える資金あり':'投資負担を確認']]);
if(tab==='earnings'){let r=x.reports.at(-1);html=r?table(['最新決算','市場予想','実績','結果'],[['売上高',unit(r.expRev),unit(r.actRev),r.revBeat?'上振れ':'下振れ'],['営業利益',unit(r.expOp),unit(r.actOp),r.opBeat?'上振れ':'下振れ'],['純利益','—',unit(r.net),'更新'],['EPS','—',money(r.eps),'更新']])+`<div class="insight">株価反応：${r.reason}</div>`:'<div class="insight">次の四半期に決算が発表されます。市場予想と実績の差が株価を動かします。</div>'}
if(tab==='news')html=(x.news.length?x.news.slice().reverse().map(n=>`<div class="history-item"><span><b>${n.title}</b><small>${n.period}</small></span><span>${n.text}</span></div>`).join(''):'<div class="empty">個別ニュースはまだありません</div>');$('#analysisContent').innerHTML=html;bindHelp()}
function table(head,rows){return`<table class="data-table"><thead><tr>${head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table>`}function unit(n){return (n/100).toFixed(1)+'億円'}
function draw(canvas,vals,color='#39d2c0'){if(!canvas||!canvas.getClientRects().length)return;let w=Math.round(canvas.getBoundingClientRect().width);if(w<2)return;let dpr=Math.min(devicePixelRatio||1,2),h=220,ctx=canvas.getContext('2d'),pixelW=Math.round(w*dpr),pixelH=Math.round(h*dpr);if(canvas.width!==pixelW)canvas.width=pixelW;if(canvas.height!==pixelH)canvas.height=pixelH;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#1d2938';ctx.lineWidth=1;for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(0,h*i/5);ctx.lineTo(w,h*i/5);ctx.stroke()}let safe=vals.length?vals:[0],min=Math.min(...safe)*.97,max=Math.max(...safe)*1.03,rr=max-min||1,pts=safe.map((v,i)=>[10+(w-20)*i/Math.max(1,safe.length-1),10+(h-25)*(1-(v-min)/rr)]),g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,color+'44');g.addColorStop(1,color+'00');ctx.beginPath();ctx.moveTo(pts[0][0],h);pts.forEach(p=>ctx.lineTo(...p));ctx.lineTo(pts.at(-1)[0],h);ctx.fillStyle=g;ctx.fill();ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke()}
function renderChart(x){let opts={price:'株価',revenue:'売上',op:'営業利益',eps:'EPS',per:'PER',roe:'ROE'};$('#chartMetrics').innerHTML=Object.entries(opts).map(([k,v])=>`<button data-metric="${k}" class="${metric===k?'active':''}">${v}</button>`).join('');$('#chartRanges').innerHTML=['1M','6M','1Y','5Y','ALL'].map(r=>`<button data-range="${r}" class="${range===r?'active':''}">${r}</button>`).join('');let vals=metric==='price'?x.history:metric==='revenue'?x.revenueHist:metric==='op'?x.opHist:metric==='eps'?x.epsHist:x.history.map(()=>metric==='per'?metrics(x).per:metrics(x).roe),n={1:4,6:24,12:48,60:240}[parseInt(range)]||vals.length;draw($('#mainChart'),vals.slice(-n));document.querySelectorAll('[data-metric]').forEach(b=>b.onclick=()=>{metric=b.dataset.metric;renderCompany()});document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{range=b.dataset.range;renderCompany()})}
function renderPortfolio(){let t=total(),rows=Object.entries(state.holdings);$('#portfolioBody').innerHTML=rows.length?rows.map(([id,h])=>{let x=state.companies.find(y=>y.id===id),v=x.price*h.qty,g=v-h.avg*h.qty;return`<tr><td>${x.name}<small>${x.ticker}</small></td><td>${h.qty}</td><td>${money(h.avg)}</td><td>${money(x.price)}</td><td>${money(h.avg*h.qty)}</td><td>${money(v)}</td><td class="${g>=0?'positive':'negative'}">${money(g)}<br>${pct(g/(h.avg*h.qty)*100)}</td><td>${money(x.dividend*h.qty)}</td></tr>`}).join(''):'<tr><td class="empty" colspan="8">保有株はありません。企業を分析して投資を始めましょう。</td></tr>';let ret=(t/1e7-1)*100,cagr=(Math.pow(t/1e7,1/Math.max(.25,state.turn/4))-1)*100;$('#portfolioMetrics').innerHTML=`総リターン <b class="${ret>=0?'positive':'negative'}">${pct(ret)}</b>`;$('#riskStats').innerHTML=`<div><span>年平均リターン</span><b>${pct(isFinite(cagr)?cagr:0)}</b></div><div><span>最大ドローダウン</span><b>${pct(-state.maxDD*100)}</b></div><div><span>受取配当</span><b>${money(state.dividends)}</b></div><div><span>売買回数</span><b>${state.trades}回</b></div>`;draw($('#assetChart'),state.assets,'#4f8cff')}
function renderHistory(){$('#historyList').innerHTML=state.history.length?state.history.slice().reverse().map(h=>`<div class="history-item"><span><b class="${h.type==='購入'?'positive':h.type==='売却'?'negative':''}">${h.type}</b> ${h.name}<small>${h.period} · ${h.detail}</small></span><strong>${h.amount?money(h.amount):''}</strong></div>`).join(''):'<div class="empty">取引・決算の記録がここに残ります。</div>'}
function openTrade(){let x=c(),h=state.holdings[x.id]?.qty||0;modal(`<h2>${x.name}を売買</h2><div class="trade-form"><div class="trade-switch"><button class="active" data-side="buy">購入</button><button data-side="sell">売却</button></div><label>株数<input id="qty" type="number" min="1" value="100"></label><div class="order-preview"><div><span>現在価格</span><b>${money(x.price)}</b></div><div><span>保有株数</span><b>${h}株</b></div><div><span>注文金額</span><b id="orderAmount">${money(x.price*100)}</b></div></div><button id="reviewOrder" class="primary">注文内容を確認</button></div>`);document.querySelectorAll('[data-side]').forEach(b=>b.onclick=()=>{tradeSide=b.dataset.side;document.querySelectorAll('[data-side]').forEach(z=>z.classList.toggle('active',z===b))});$('#qty').oninput=()=>$('#orderAmount').textContent=money(x.price*Math.max(0,+$('#qty').value));$('#reviewOrder').onclick=reviewOrder}
function reviewOrder(){let x=c(),qty=Math.max(1,parseInt($('#qty').value)||1),amount=x.price*qty,h=state.holdings[x.id]?.qty||0;if(tradeSide==='buy'&&amount>state.cash)return toast('現金が不足しています');if(tradeSide==='sell'&&qty>h)return toast('保有株数を超えています');modal(`<h2>注文確認</h2><div class="confirm-box">${tradeSide==='buy'?'購入':'売却'}：${x.name} ${qty}株<br>注文金額：${money(amount)}<br><small>全額投資や数量の入力間違いがないか確認してください。</small></div><button id="confirmOrder" class="primary">確定する</button>`);$('#confirmOrder').onclick=()=>executeTrade(x,qty,amount)}
function executeTrade(x,qty,amount){let h=state.holdings[x.id]||{qty:0,avg:0};if(tradeSide==='buy'){h.avg=(h.avg*h.qty+amount)/(h.qty+qty);h.qty+=qty;state.holdings[x.id]=h;state.cash-=amount}else{h.qty-=qty;state.cash+=amount;if(!h.qty)delete state.holdings[x.id];else state.holdings[x.id]=h}state.trades++;state.history.push({type:tradeSide==='buy'?'購入':'売却',name:x.name,period:`${state.year} Q${state.q}`,detail:`${qty}株 × ${money(x.price)}`,amount});closeModal();toast('注文が約定しました');render()}
function advance(){if(state.turn>=40)return showResult();let event=EVENTS[Math.floor(Math.random()*EVENTS.length)],noiseScale={beginner:.65,normal:1,advanced:1.2}[state.difficulty];state.sentiment=Math.max(-.12,Math.min(.12,state.sentiment*.5+(Math.random()-.5)*.08+(event.all||0)));if(event.rate)state.rate=Math.min(3,state.rate+event.rate);state.companies.forEach(x=>{x.prevPrice=x.price;let cyc=[.025,.045,-.01,-.045][state.cycle],sectorImpact=event.tags?.includes(x.sector)?event.v||0:0,g=(x.baseGrowth/4)+cyc+(event.margin||0)+(Math.random()-.5)*.08*noiseScale;x.growth=g*4;x.revenue*=1+g;x.margin=Math.max(.01,x.margin+(Math.random()-.5)*.012+(event.margin||0));x.op=x.revenue*x.margin;x.ordinary=x.op*.94;x.net=x.op*(.61+(Math.random()-.5)*.08);x.gross=x.revenue*(.4+(x.id.charCodeAt(0)%5)*.035);x.ocf=x.op*(.9+Math.random()*.35);x.icf=-x.op*(.35+Math.random()*.55);x.fcf=x.ocf+x.icf;x.financing=-x.net*.18;x.cash=Math.max(0,x.cash+x.fcf*.2);x.equity+=Math.max(0,x.net-x.dividend*x.shares);x.capital=x.equity*.96;x.assets=x.equity+x.debt+x.cash*.3;let expRev=x.revenue*(.97+Math.random()*.06),expOp=x.op*(.94+Math.random()*.12),actRev=x.revenue,actOp=x.op,revBeat=actRev>=expRev,opBeat=actOp>=expOp,expect=(revBeat?1:-1)+(opBeat?1:-1),m=metrics(x),valuation=(x.targetPE/m.per-1)*.05,rateHit=(m.per>25?-(state.rate-.5)*.012:0),eventHit=sectorImpact+(event.all||0)+(event.growth&&m.per>25?event.growth:0),move=g*.45+expect*.028+valuation+rateHit+eventHit+state.sentiment+(Math.random()-.5)*.09*noiseScale;x.price=Math.max(80,Math.round(x.price*(1+Math.max(-.28,Math.min(.28,move)))));let reason=`${revBeat&&opBeat?'予想を上回る決算':!revBeat&&!opBeat?'市場予想を下回る決算':'売上・利益で評価が分かれる決算'}。${move>=0?'成長・期待が買われた':'期待との差やバリュエーションが重し'}`;x.reports.push({expRev,expOp,actRev,actOp,net:x.net,eps:x.net/x.shares,revBeat,opBeat,reason});x.news.push({title:event.t,text:event.d,period:`${state.year} Q${state.q}`});x.history.push(x.price);x.revenueHist.push(x.revenue);x.opHist.push(x.op);x.epsHist.push(x.net/x.shares);if(x.history.length>161)x.history.shift()});
 if(state.q===4){Object.entries(state.holdings).forEach(([id,h])=>{let x=state.companies.find(y=>y.id===id),d=x.dividend*h.qty;state.cash+=d;state.dividends+=d});state.year++;state.q=1;state.cycle=(state.cycle+1)%4}else state.q++;state.turn++;let t=total();state.assets.push(t);state.peak=Math.max(state.peak,t);state.maxDD=Math.max(state.maxDD,1-t/state.peak);state.news.push({title:event.t,text:event.d,period:`${state.year} Q${state.q}`});state.history.push({type:'決算',name:event.t,period:`${state.year} Q${state.q}`,detail:event.d});$('#tickerNews').textContent=`${event.t}｜${event.d}`;if(state.turn%4===2)showQuiz();if(state.turn>=40)showResult();render()}
function showQuiz(){let x=state.companies[(state.turn*7)%state.companies.length],m=metrics(x);modal(`<small>INVESTMENT JUDGMENT</small><h2>この企業をどう判断しますか？</h2><p>${x.name}｜PER ${m.per.toFixed(1)}倍・ROE ${m.roe.toFixed(1)}%・売上YoY ${pct(m.yoyRev)}・営業利益YoY ${pct(m.yoyOp)}</p><button class="quiz-choice" data-q="0">A. PERだけを見てすぐ全額投資</button><button class="quiz-choice" data-q="1">B. 成長率・利益率・財務・期待との差を追加確認</button><button class="quiz-choice" data-q="2">C. ROEだけで優良企業と断定</button><div id="quizExplain"></div>`);document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{$('#quizExplain').innerHTML=`<div class="insight">${b.dataset.q==='1'?'慎重で良い判断です。':'単一指標だけでは判断できません。'} PERは成長期待、ROEは負債、売上は利益率と組み合わせて見ましょう。</div>`})}
function showResult(){let t=total(),years=10,cagr=(Math.pow(t/1e7,1/years)-1)*100,style=Object.keys(state.holdings).length<=2?'集中投資型':state.dividends>3e5?'高配当型':state.cash/t>.5?'慎重型':'バランス型';modal(`<div class="welcome"><small>10 YEARS COMPLETE</small><h2>運用結果</h2><div class="metrics-grid">${metricCard('初期資産',money(1e7))}${metricCard('最終資産',money(t))}${metricCard('利益',money(t-1e7))}${metricCard('年平均リターン',pct(cagr))}${metricCard('最大DD',pct(-state.maxDD*100))}${metricCard('受取配当',money(state.dividends))}${metricCard('売買回数',state.trades+'回')}</div><h3>あなたは「${style}」</h3><p>結果だけでなく、どの数字を根拠に判断したかが投資家としての成長です。</p><button id="restart" class="primary">新しく始める</button></div>`);$('#restart').onclick=()=>{localStorage.removeItem(KEY);location.reload()}}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').classList.add('open')}function closeModal(){$('#modal').classList.remove('open')}function toast(s){let x=$('#toast');x.textContent=s;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}function bindHelp(){document.querySelectorAll('[data-help]').forEach(b=>b.onclick=()=>modal(`<h2>${b.dataset.help}</h2><p style="line-height:1.8">${EXPLAIN[b.dataset.help]}</p>`))}
function init(){let sectors=['すべて',...new Set(state.companies.map(x=>x.sector))];$('#filters').innerHTML=sectors.map(s=>`<button data-sector="${s}" class="${s===sector?'active':''}">${s}</button>`).join('');document.querySelectorAll('[data-sector]').forEach(b=>b.onclick=()=>{sector=b.dataset.sector;init();renderList()});document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(z=>z.classList.toggle('active',z===b));document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));let view=$('#'+b.dataset.view+'View');view.classList.add('active');requestAnimationFrame(()=>{if(b.dataset.view==='market')renderCompany();if(b.dataset.view==='portfolio')renderPortfolio()})});document.querySelectorAll('#analysisTabs button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('#analysisTabs button').forEach(z=>z.classList.toggle('active',z===b));renderCompany()});$('#search').oninput=renderList;$('#tradeOpen').onclick=openTrade;$('#advanceBtn').onclick=advance;$('#settingsBtn').onclick=()=>modal(`<h2>ゲーム設定</h2><p>難易度：${state.difficulty}</p><button id="resetGame" class="primary">セーブを消して最初から</button>`);document.addEventListener('click',e=>{if(e.target.matches('[data-close]'))closeModal();if(e.target.id==='resetGame'&&confirm('全データを削除しますか？')){localStorage.removeItem(KEY);location.reload()}});$('#startBtn').onclick=()=>{state.difficulty=$('#difficulty').value;state.started=true;$('#welcome').style.display='none';save();render()};if(state.started)$('#welcome').style.display='none';let resizeFrame=0;addEventListener('resize',()=>{cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(()=>{if($('#marketView').classList.contains('active'))renderCompany();if($('#portfolioView').classList.contains('active'))renderPortfolio()})},{passive:true});render()}
init();})();
