const STOCKS=[
 {id:'mirai',market:'JP',name:'ミライAI',ticker:'4388',price:3280,sector:'AI・ソフトウェア',per:42.8,pbr:8.4,roe:21.5,dividend:.4,vol:.035,growth:.0018,tags:['tech','ai'],note:'生成AIサービスを企業向けに提供。高成長が期待される一方、値動きは大きめです。'},
 {id:'sakura',market:'JP',name:'さくら銀行',ticker:'8350',price:1260,sector:'銀行',per:11.2,pbr:.8,roe:7.4,dividend:3.2,vol:.016,growth:.0004,tags:['bank'],note:'国内大手銀行。金利上昇は利ざや改善への期待につながります。'},
 {id:'hinode',market:'JP',name:'日の出リテール',ticker:'8264',price:2140,sector:'小売',per:18.6,pbr:1.7,roe:9.8,dividend:2.1,vol:.019,growth:.0005,tags:['retail','cyclical'],note:'全国に生活用品店を展開。個人消費や景気の影響を受けます。'},
 {id:'aoba',market:'JP',name:'青葉ライフ',ticker:'4522',price:4870,sector:'ヘルスケア',per:24.1,pbr:2.6,roe:12.1,dividend:2.4,vol:.011,growth:.0007,tags:['defensive'],note:'医薬品と健康食品を扱うディフェンシブ企業。比較的安定した値動きです。'},
 {id:'nova',market:'US',name:'Nova Chips',ticker:'NVCH',price:19200,sector:'半導体',per:36.5,pbr:11.2,roe:29.4,dividend:.2,vol:.032,growth:.0015,tags:['tech','chip','ai'],note:'AI向け半導体を設計。成長力が高い反面、市況の波も大きい銘柄です。'},
 {id:'atlas',market:'US',name:'Atlas Energy',ticker:'ATLE',price:7450,sector:'エネルギー',per:9.8,pbr:1.4,roe:16.8,dividend:4.5,vol:.021,growth:.0003,tags:['energy'],note:'石油・天然ガスを生産。原油価格が業績と株価を左右します。'},
 {id:'skyway',market:'US',name:'Skyway Air',ticker:'SKYA',price:5680,sector:'航空',per:15.4,pbr:2.2,roe:14.3,dividend:1.1,vol:.026,growth:.0005,tags:['airline','cyclical'],note:'国際線を中心とする航空会社。景気と燃料価格の影響を受けます。'},
 {id:'harbor',market:'US',name:'Harbor Utilities',ticker:'HBRU',price:4120,sector:'公益',per:17.3,pbr:1.5,roe:8.7,dividend:3.8,vol:.009,growth:.0002,tags:['defensive'],note:'電力・水道を運営。景気に左右されにくく、配当も比較的安定しています。'}
];
const EVENTS=[
 {title:'CPI上昇',text:'金利上昇観測でハイテク株に逆風。銀行には追い風です。',effects:{tech:-.035,bank:.03,cyclical:-.012}},
 {title:'CPI低下',text:'インフレ鈍化への期待から成長株が買われています。',effects:{tech:.03,bank:-.012,cyclical:.015}},
 {title:'FRBが利上げ',text:'金利上昇。銀行株が上昇し、成長株は調整しています。',effects:{bank:.035,tech:-.04}},
 {title:'FRBが利下げ',text:'資金調達環境の改善期待で成長株が上昇しています。',effects:{bank:-.02,tech:.04,cyclical:.02}},
 {title:'原油価格上昇',text:'エネルギー株に追い風、航空株には燃料費負担が重荷です。',effects:{energy:.06,airline:-.05}},
 {title:'AIブーム',text:'AI関連への投資が加速。AI・半導体株が注目されています。',effects:{ai:.075,chip:.055}},
 {title:'半導体不足',text:'供給制約への警戒から半導体株が売られています。',effects:{chip:-.06,tech:-.015}},
 {title:'景気後退懸念',text:'景気敏感株が下落し、ディフェンシブ株に資金が向かいます。',effects:{cyclical:-.05,retail:-.035,defensive:.025}},
 {title:'好決算シーズン',text:'企業業績が予想を上回り、市場全体が上昇しています。',effects:{all:.025}},
 {title:'企業の不祥事',text:'ランダムな1社に悪材料。リスク分散の大切さが試されます。',effects:{random:-.12}}
];
const TERMS={売上高:'商品やサービスを販売して得た金額の合計。会社の事業規模を見る基本的な数字です。',売上総利益:'売上高から商品の仕入れや製造に直接かかった費用を引いた利益です。',粗利:'売上総利益の別名。商品そのものがどれだけ利益を生むかを表します。',営業利益:'粗利から人件費や広告費など本業の運営費を引いた利益です。',経常利益:'営業利益に受取利息など、本業以外で普段発生する損益を加えた利益です。',純利益:'税金などをすべて差し引き、最終的に会社に残った利益です。',PER:'株価収益率。株価が1株利益の何倍かを示し、期待や割高・割安を考える目安です。',PBR:'株価純資産倍率。株価が1株純資産の何倍かを示します。',ROE:'自己資本利益率。株主のお金を使ってどれだけ効率よく利益を出したかを示します。',ROA:'総資産利益率。会社が持つすべての資産をどれだけ効率よく利益につなげたかを示します。',EPS:'1株当たり純利益。会社の利益を発行済み株式数で割った数字です。',BPS:'1株当たり純資産。会社の純資産を発行済み株式数で割った数字です。',配当利回り:'1年間の配当金が株価に対して何％かを示します。',時価総額:'株価×発行済み株式数。市場が評価する会社全体の価値です。',ETF:'取引所で株のように売買できる投資信託。複数資産にまとめて分散投資できます。',投資信託:'投資家から集めたお金を専門家がまとめて運用する金融商品です。',長期金利:'主に10年国債の利回り。住宅ローンや企業の借入金利にも影響します。',政策金利:'中央銀行が景気や物価を調整するために設定・誘導する短期金利です。',CPI:'消費者物価指数。家庭が買う商品やサービスの価格変化を表すインフレ指標です。',PPI:'生産者物価指数。企業間で取引される商品の価格変化を表します。'};
const QUIZZES=[
 {q:'CPIが予想より高かった場合、一般的に金利はどうなりやすい？',a:['上がりやすい','下がりやすい','必ず変わらない'],correct:0,e:'物価上昇を抑えるため、中央銀行が利上げを検討しやすくなります。'},
 {q:'複数の銘柄に投資する主な目的は？',a:['利益を保証する','リスクを分散する','税金をなくす'],correct:1,e:'値動きの異なる資産を持つことで、1銘柄の下落による影響を和らげます。'},
 {q:'PERが表しているものは？',a:['株価が1株利益の何倍か','会社の借金総額','年間の売上個数'],correct:0,e:'PERは株価÷EPS。利益に対して株価が何倍まで買われているかを示します。'},
 {q:'含み益とはどんな利益？',a:['売却して確定した利益','まだ売却していない値上がり益','受け取った配当'],correct:1,e:'保有中の株が取得価格より上がっている状態の、未確定の利益です。'},
 {q:'原油価格上昇が航空会社に与えやすい影響は？',a:['燃料費増加の逆風','必ず売上が倍増','影響は一切ない'],correct:0,e:'航空燃料の費用が増えるため、一般に利益を圧迫する要因です。'}
];
const KEY='stockQuestSaveV1'; let selected='mirai',marketFilter='all',side='buy',answered=false;
function fresh(){return{cash:1000000,day:1,date:'2026-01-05',difficulty:'beginner',points:0,holdings:{},history:[],prices:Object.fromEntries(STOCKS.map(s=>[s.id,s.price])),priceHistory:Object.fromEntries(STOCKS.map(s=>[s.id,[s.price]])),assets:[1000000],realized:0,achievements:[]}}
let state=(()=>{try{return JSON.parse(localStorage.getItem(KEY))||fresh()}catch{return fresh()}})();
const $=s=>document.querySelector(s),yen=n=>'¥'+Math.round(n).toLocaleString('ja-JP'),pct=n=>(n>=0?'+':'')+n.toFixed(2)+'%';
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function stock(id){return STOCKS.find(s=>s.id===id)}
function positionValue(){return Object.entries(state.holdings).reduce((v,[id,h])=>v+state.prices[id]*h.qty,0)}
function unrealized(){return Object.entries(state.holdings).reduce((v,[id,h])=>v+(state.prices[id]-h.avg)*h.qty,0)}
function total(){return state.cash+positionValue()}
function change(id){let h=state.priceHistory[id];return h.length<2?0:(h.at(-1)/h.at(-2)-1)*100}
function cls(n){return n>0?'positive':n<0?'negative':''}
function render(){renderSummary();renderStocks();renderDetail();renderTrade();renderPortfolio();renderHistory();renderPerformance();renderQuiz();save()}
function renderSummary(){const t=total(),ret=(t/1000000-1)*100;$一下('#totalAssets').textContent=yen(t);$('#cash').textContent=yen(state.cash);$('#stockValue').textContent=yen(positionValue());$('#positionCount').textContent=Object.keys(state.holdings).length+'銘柄を保有';$('#unrealized').textContent=yen(unrealized());$('#unrealized').className=cls(unrealized());$('#realized').textContent='実現損益 '+yen(state.realized);$('#totalReturn').textContent='総リターン '+pct(ret);$('#goalPercent').textContent=Math.min(100,t/100000000*100).toFixed(1)+'%';$('#goalBar').style.width=Math.min(100,t/100000000*100)+'%';$('#rankText').textContent='ランク：'+(t>=100000000?'伝説の投資家':t>=10000000?'マーケットマスター':t>=2000000?'成長投資家':'ルーキー投資家');$('#dateLabel').textContent=new Date(state.date).toLocaleDateString('ja-JP',{year:'numeric',month:'long',day:'numeric'});$('#difficultyLabel').textContent={beginner:'初心者',normal:'標準',hard:'チャレンジ'}[state.difficulty]+'モード';}
function renderStocks(){const list=STOCKS.filter(s=>marketFilter==='all'||s.market===marketFilter);$('#stockList').innerHTML=list.map(s=>`<button class="stock-row ${s.id===selected?'active':''}" data-id="${s.id}"><span><b>${s.name}</b><small>${s.market==='JP'?'🇯🇵':'🇺🇸'} ${s.ticker} · ${s.sector}</small></span><span class="stock-price"><b>${yen(state.prices[s.id])}</b><small class="change ${cls(change(s.id))}">${pct(change(s.id))}</small></span></button>`).join('');document.querySelectorAll('.stock-row').forEach(b=>b.onclick=()=>{selected=b.dataset.id;$('#tradeStock').value=selected;render()})}
function drawLine(canvas,values,color='#08785d',fill=true){const dpr=devicePixelRatio||1,w=canvas.clientWidth,h=Number(canvas.getAttribute('height'));canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);const min=Math.min(...values)*.98,max=Math.max(...values)*1.02,range=max-min||1,pad=12;c.strokeStyle='#e8ede9';c.lineWidth=1;for(let i=1;i<4;i++){c.beginPath();c.moveTo(0,h*i/4);c.lineTo(w,h*i/4);c.stroke()}const pts=values.map((v,i)=>[pad+(w-pad*2)*(i/Math.max(1,values.length-1)),pad+(h-pad*2)*(1-(v-min)/range)]);if(fill){const g=c.createLinearGradient(0,0,0,h);g.addColorStop(0,color+'33');g.addColorStop(1,color+'00');c.beginPath();c.moveTo(pts[0][0],h);pts.forEach(p=>c.lineTo(...p));c.lineTo(pts.at(-1)[0],h);c.fillStyle=g;c.fill()}c.beginPath();pts.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.strokeStyle=color;c.lineWidth=2.5;c.stroke()}
function renderDetail(){const s=stock(selected),ch=change(s.id);$('#selectedTicker').textContent=(s.market==='JP'?'TOKYO ':'NASDAQ ')+s.ticker;$('#selectedName').textContent=s.name;$('#selectedSector').textContent=s.sector;$('#selectedPrice').textContent=yen(state.prices[s.id]);$('#selectedChange').textContent=pct(ch)+' 前日比';$('#selectedChange').className=cls(ch);$('#fundamentals').innerHTML=[['PER',s.per+'倍'],['PBR',s.pbr+'倍'],['ROE',s.roe+'%'],['配当利回り',s.dividend+'%']].map(x=>`<div class="fundamental"><button data-term="${x[0]}">${x[0]} ⓘ</button><strong>${x[1]}</strong></div>`).join('');$('#companyNote').textContent=s.note;drawLine($('#priceChart'),state.priceHistory[s.id],ch<0?'#d94b55':'#08785d');bindTerms()}
function renderTrade(){const sel=$('#tradeStock');sel.innerHTML=STOCKS.map(s=>`<option value="${s.id}">${s.name}（${s.ticker}）</option>`).join('');sel.value=selected;const q=Math.max(1,parseInt($('#quantity').value)||1),p=state.prices[selected],h=state.holdings[selected];$('#orderPrice').textContent=yen(p);$('#orderTotal').textContent=yen(p*q);$('#availableLabel').textContent=side==='buy'?'購入可能額':'売却可能株数';$('#availableValue').textContent=side==='buy'?yen(state.cash):(h?.qty||0)+'株';$('#orderBtn').textContent='この内容で'+(side==='buy'?'購入':'売却');$('#orderBtn').style.background=side==='buy'?'#08785d':'#d94b55'}
function renderPortfolio(){const rows=Object.entries(state.holdings);$('#portfolioBody').innerHTML=rows.length?rows.map(([id,h])=>{const s=stock(id),p=state.prices[id],gain=(p-h.avg)*h.qty;return`<tr><td><b>${s.name}</b><br><small>${s.ticker}</small></td><td>${h.qty}</td><td>${yen(h.avg)}</td><td>${yen(p)}</td><td>${yen(p*h.qty)}</td><td class="${cls(gain)}">${yen(gain)}</td></tr>`}).join(''):'<tr><td colspan="6" class="empty">まだ保有銘柄はありません。気になる銘柄を1株買ってみましょう。</td></tr>'}
function renderHistory(){const box=$('#historyList');box.innerHTML=state.history.length?state.history.slice().reverse().map(h=>`<div class="history-item"><span><b class="${h.side==='購入'?'positive':'negative'}">${h.side}</b> ${stock(h.id).name}<small>${h.date} · ${h.qty}株 × ${yen(h.price)}</small></span><strong>${yen(h.qty*h.price)}</strong></div>`).join(''):'<p class="empty">取引すると、ここに記録されます。</p>'}
function renderPerformance(){const vals=state.assets,peak=Math.max(...vals),dd=(Math.min(...vals.map((v,i)=>v/Math.max(...vals.slice(0,i+1))-1))*100),ret=total()/1000000-1,annual=(Math.pow(Math.max(.01,1+ret),365/Math.max(1,state.day-1))-1)*100;$('#drawdown').textContent=dd.toFixed(2)+'%';$('#annualized').textContent=(isFinite(annual)?annual:0).toFixed(2)+'%';const changes=vals.slice(1).map((v,i)=>Math.abs(v/vals[i]-1)),risk=changes.length?changes.reduce((a,b)=>a+b,0)/changes.length:0;$('#riskRating').textContent=risk>.025?'高':risk>.012?'中':'低';drawLine($('#assetChart'),vals,'#4a70d8')}
function renderQuiz(){const q=QUIZZES[state.day%QUIZZES.length];$('#points').textContent=state.points+' pt';$('#quizBox').innerHTML=`<div class="quiz-content"><h3>Q. ${q.q}</h3><div class="answers">${q.a.map((a,i)=>`<button class="answer" data-answer="${i}">${String.fromCharCode(65+i)}. ${a}</button>`).join('')}</div><div id="quizExplanation"></div></div>`;answered=false;document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>answerQuiz(b,q))}
function answerQuiz(btn,q){if(answered)return;answered=true;const n=+btn.dataset.answer;btn.classList.add(n===q.correct?'correct':'wrong');document.querySelectorAll('.answer')[q.correct].classList.add('correct');if(n===q.correct){state.points+=10;toast('正解！ 10ポイント獲得')}$('#quizExplanation').innerHTML=`<div class="explanation"><b>${n===q.correct?'正解！':'おしい！'}</b><br>${q.e}</div>`;$('#points').textContent=state.points+' pt';save()}
function bindTerms(){document.querySelectorAll('[data-term]').forEach(b=>b.onclick=()=>openTerm(b.dataset.term))}
function openTerm(t){$('#termTitle').textContent=t;$('#termDescription').textContent=TERMS[t];$('#termModal').classList.add('open');$('#termModal').setAttribute('aria-hidden','false')}
function trade(){const q=Math.max(1,parseInt($('#quantity').value)||1),p=state.prices[selected],h=state.holdings[selected]||{qty:0,avg:0};if(side==='buy'){if(p*q>state.cash)return message('所持金が不足しています。',false);const totalCost=h.avg*h.qty+p*q;h.qty+=q;h.avg=totalCost/h.qty;state.holdings[selected]=h;state.cash-=p*q}else{if(q>h.qty)return message('保有株数以上は売却できません。',false);state.realized+=(p-h.avg)*q;state.cash+=p*q;h.qty-=q;if(h.qty===0)delete state.holdings[selected];else state.holdings[selected]=h}state.history.push({date:state.date,id:selected,side:side==='buy'?'購入':'売却',qty:q,price:p});message(`${stock(selected).name}を${q}株${side==='buy'?'購入':'売却'}しました。`,true);render()}
function message(t,ok){$('#orderMessage').textContent=t;$('#orderMessage').className='order-message '+(ok?'positive':'negative');if(ok)toast(t)}
function nextDay(){const scale={beginner:.65,normal:1,hard:1.5}[state.difficulty],event=Math.random()<.72?EVENTS[Math.floor(Math.random()*EVENTS.length)]:null,randomTarget=Math.floor(Math.random()*STOCKS.length);STOCKS.forEach((s,i)=>{let impact=s.growth+(Math.random()+Math.random()+Math.random()-1.5)*s.vol*scale;if(event){impact+=(event.effects.all||0);s.tags.forEach(t=>impact+=(event.effects[t]||0));if(event.effects.random&&i===randomTarget)impact+=event.effects.random}const p=Math.max(100,Math.round(state.prices[s.id]*(1+impact)));state.prices[s.id]=p;state.priceHistory[s.id].push(p);if(state.priceHistory[s.id].length>45)state.priceHistory[s.id].shift()});state.day++;const d=new Date(state.date);d.setDate(d.getDate()+1);state.date=d.toISOString().slice(0,10);state.assets.push(total());if(state.assets.length>180)state.assets.shift();$('#eventTitle').textContent=event?event.title:'静かな相場';$('#eventText').textContent=event?event.text:'大きなニュースはなく、銘柄ごとの材料で動きました。';checkAchievements();render()}
function checkAchievements(){const candidates=[['first',state.history.length>0,'はじめての取引'],['diversify',Object.keys(state.holdings).length>=3,'分散投資家'],['million',total()>=1100000,'資産110万円'],['scholar',state.points>=50,'投資の学び手']];candidates.forEach(([id,ok,name])=>{if(ok&&!state.achievements.includes(id)){state.achievements.push(id);toast('実績解除：'+name)}})}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function init(){
 $('#termCloud').innerHTML=Object.keys(TERMS).map(t=>`<button class="term" data-term="${t}">${t}</button>`).join('');bindTerms();
 document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');marketFilter=b.dataset.market;renderStocks()});
 document.querySelectorAll('.trade-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.trade-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');side=b.dataset.side;renderTrade()});
 $('#tradeStock').onchange=e=>{selected=e.target.value;render()};$('#quantity').oninput=renderTrade;$('#minusQty').onclick=()=>{$('#quantity').value=Math.max(1,+$('#quantity').value-1);renderTrade()};$('#plusQty').onclick=()=>{$('#quantity').value=(+$('#quantity').value||0)+1;renderTrade()};document.querySelectorAll('[data-qty]').forEach(b=>b.onclick=()=>{$('#quantity').value=b.dataset.qty;renderTrade()});$('#maxQty').onclick=()=>{$('#quantity').value=side==='buy'?Math.max(1,Math.floor(state.cash/state.prices[selected])):Math.max(1,state.holdings[selected]?.qty||1);renderTrade()};$('#orderBtn').onclick=trade;$('#nextDayBtn').onclick=nextDay;
 $('#resetBtn').onclick=()=>{if(confirm('すべての進行を消して最初から始めますか？')){localStorage.removeItem(KEY);state=fresh();location.reload()}};
 document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.remove('open'));$('#startBtn').onclick=()=>{state.difficulty=$('#difficulty').value;$('#welcomeModal').classList.remove('open');save();render()};
 if(!localStorage.getItem(KEY)){$('#welcomeModal').classList.add('open');$('#welcomeModal').setAttribute('aria-hidden','false')}render();addEventListener('resize',()=>{renderDetail();renderPerformance()})
}
// Typo-resistant alias used by the compact dashboard renderer.
window.$一下=$;
init();
